# Generated by Django 2.0.7 on 2020-02-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercode',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
