# Generated by Django 3.2.4 on 2021-06-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeuser', '0002_auto_20210621_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='programador',
            name='imagen_perfil',
            field=models.ImageField(blank=True, upload_to='Imagenes'),
        ),
    ]
