# Generated by Django 3.2.4 on 2021-06-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeuser', '0003_programador_imagen_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programador',
            name='imagen_perfil',
            field=models.ImageField(default='anonimo.png', upload_to='Imagenes'),
        ),
    ]
