# Generated by Django 2.0.7 on 2020-02-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_codigo', models.CharField(max_length=30)),
                ('nombre_etiqueta', models.CharField(max_length=30)),
                ('codigo_guardado', models.TextField()),
            ],
        ),
    ]
