# Generated by Django 3.0.3 on 2020-02-14 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codigo', '0002_tablatecnicos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tablatecnicos',
        ),
    ]
