# Generated by Django 2.0.7 on 2020-02-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=30)),
                ('birth', models.CharField(max_length=30)),
                ('profetion', models.CharField(max_length=30)),
                ('aboutme', models.TextField()),
                ('image_user', models.ImageField(upload_to='')),
            ],
        ),
    ]
